# Generated by Django 5.0.7 on 2026-02-07 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('IMAGE', 'Изображение'), ('VIDEO', 'Видео')], max_length=10, verbose_name='Тип ассета')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='URL файла')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='URL превью')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('prompt_text', models.TextField(blank=True, verbose_name='Текст промпта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='boxes.box', verbose_name='Бокс')),
            ],
            options={
                'verbose_name': 'Ассет',
                'verbose_name_plural': 'Ассеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
