# Generated by Django 5.0.7 on 2026-02-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ai_model',
            field=models.ForeignKey(blank=True, help_text='Модель, которая сгенерировала этот ассет', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assets', to='ai_providers.aimodel', verbose_name='AI Модель'),
        ),
        migrations.AddField(
            model_name='asset',
            name='generation_config',
            field=models.JSONField(blank=True, default=dict, help_text='Выбранные параметры генерации (width, height, steps, и т.д.)', verbose_name='Конфигурация генерации'),
        ),
        migrations.AddField(
            model_name='asset',
            name='seed',
            field=models.IntegerField(blank=True, help_text='Seed для воспроизводимости генерации', null=True, verbose_name='Seed'),
        ),
    ]
