# Generated by Django 5.0.7 on 2026-02-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_ai_model_asset_generation_config_asset_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='error_message',
            field=models.TextField(blank=True, help_text='Детали ошибки при генерации', verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='asset',
            name='external_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Task ID от Kie.ai или другого провайдера', max_length=255, verbose_name='ID задачи у провайдера'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent_asset',
            field=models.ForeignKey(blank=True, help_text='Исходный ассет для img2vid или вариаций', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_assets', to='assets.asset', verbose_name='Родительский ассет'),
        ),
        migrations.AddField(
            model_name='asset',
            name='source_type',
            field=models.CharField(choices=[('GENERATED', 'Сгенерировано AI'), ('UPLOADED', 'Загружено пользователем'), ('IMG2VID', 'Img2Vid преобразование')], default='GENERATED', help_text='Способ создания ассета', max_length=20, verbose_name='Тип источника'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('PROCESSING', 'Обработка'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], default='PENDING', help_text='Статус генерации ассета', max_length=20, verbose_name='Статус'),
        ),
    ]
