# Generated by Django 5.0.7 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_error_message_asset_external_task_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['order_index', 'created_at'], 'verbose_name': 'Ассет', 'verbose_name_plural': 'Ассеты'},
        ),
        migrations.AddField(
            model_name='asset',
            name='order_index',
            field=models.IntegerField(default=0, help_text='Порядок отображения ассета внутри бокса', verbose_name='Порядковый номер'),
        ),
    ]
