# Generated by Django 5.0.7 on 2026-02-08 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(help_text='Имя клиента, оставившего комментарий', max_length=100, verbose_name='Имя автора')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('is_read', models.BooleanField(default=False, help_text='Отметка о прочтении комментария', verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='boxes.box', verbose_name='Бокс')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный токен для публичного доступа', unique=True, verbose_name='Токен')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Если пусто — без срока действия', null=True, verbose_name='Срок действия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Публичная ссылка',
                'verbose_name_plural': 'Публичные ссылки',
                'ordering': ['-created_at'],
            },
        ),
    ]
