# Generated by Django 5.0.7 on 2026-03-31 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_add_preview_url_upload_keys_uploading_status'),
        ('scenes', '0005_fix_parent_cascade_db_constraint'),
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='elements',
            field=models.ManyToManyField(blank=True, related_name='shared_links', to='elements.element', verbose_name='Элементы'),
        ),
        migrations.AddField(
            model_name='sharedlink',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scenes.scene', verbose_name='Группа'),
        ),
    ]
