# Generated by Django 5.0.7 on 2026-04-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_add_preview_url_upload_keys_uploading_status'),
        ('sharing', '0003_alter_comment_options_comment_author_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedlink',
            name='display_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ElementReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36)),
                ('value', models.CharField(choices=[('like', '👍'), ('dislike', '👎')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='elements.element')),
            ],
            options={
                'unique_together': {('element', 'session_id')},
            },
        ),
    ]
