# Generated by Django 5.0.7 on 2026-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_sharedlink_display_preferences_elementreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementreaction',
            name='author_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
