# Generated by Django 5.0.7 on 2026-04-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_elementreaction_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Системный комментарий'),
        ),
    ]
