# Generated by Django 5.0.7 on 2026-04-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0012_simplify_approval_statuses'),
        ('sharing', '0006_add_is_system_to_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36)),
                ('author_name', models.CharField(default='', max_length=100)),
                ('action', models.CharField(choices=[('approved', 'Согласовано'), ('changes_requested', 'На доработку'), ('rejected', 'Отклонено')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='elements.element')),
            ],
            options={
                'unique_together': {('element', 'session_id')},
            },
        ),
    ]
