# Generated by Django 5.0.7 on 2026-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_add_element_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
