# Generated by Django 5.0.7 on 2026-04-13 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0012_simplify_approval_statuses'),
        ('scenes', '0005_fix_parent_cascade_db_constraint'),
        ('sharing', '0008_comment_session_id_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_single_target',
        ),
        migrations.AddField(
            model_name='comment',
            name='shared_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sharing.sharedlink'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('element__isnull', True), ('scene__isnull', False), ('shared_link__isnull', True)), models.Q(('element__isnull', False), ('scene__isnull', True), ('shared_link__isnull', True)), models.Q(('element__isnull', True), ('scene__isnull', True), ('shared_link__isnull', False)), _connector='OR'), name='comment_single_target'),
        ),
    ]
