# Generated by Django 5.0.7 on 2026-02-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название провайдера')),
                ('base_url', models.URLField(help_text='Базовый URL API, например https://api.kie.ai', max_length=500, verbose_name='Базовый URL API')),
                ('api_key', models.CharField(blank=True, help_text='API ключ для авторизации (опционально)', max_length=255, verbose_name='API ключ')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать ли этот провайдер', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'AI Провайдер',
                'verbose_name_plural': 'AI Провайдеры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Nano Banana, Seedance 1.5 Pro', max_length=100, verbose_name='Название модели')),
                ('model_type', models.CharField(choices=[('IMAGE', 'Изображение'), ('VIDEO', 'Видео')], max_length=10, verbose_name='Тип модели')),
                ('api_endpoint', models.CharField(help_text='Путь эндпоинта, например /v1/generate или /nano-banana', max_length=255, verbose_name='Путь эндпоинта')),
                ('request_schema', models.JSONField(blank=True, default=dict, help_text='Полная структура запроса с плейсхолдерами {{variable}}, например: {"prompt": "{{prompt}}", "width": {{width}}}', verbose_name='Схема запроса')),
                ('parameters_schema', models.JSONField(blank=True, default=dict, help_text='Описание параметров для UI: типы, опции, дефолты. Например: {"width": {"type": "select", "options": [512, 1024], "default": 1024}}', verbose_name='Схема параметров')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать ли эту модель', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai_providers.aiprovider', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'AI Модель',
                'verbose_name_plural': 'AI Модели',
                'ordering': ['provider', 'name'],
            },
        ),
    ]
