# Generated by Django 5.0.7 on 2026-03-12 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0003_aimodel_pricing_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('ui_semantic', models.CharField(max_length=100)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('enum', 'Enum'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean')], max_length=20)),
                ('default_ui_control', models.CharField(blank=True, default='', max_length=100)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('base_options', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('can_participate_in_pricing', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModelPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('fixed', 'Fixed'), ('lookup', 'Lookup')], default='fixed', max_length=20)),
                ('dimensions', models.JSONField(blank=True, default=list)),
                ('raw_lookup', models.JSONField(blank=True, default=dict)),
                ('compiled_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_config', to='ai_providers.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelParameterBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(max_length=100)),
                ('request_path', models.CharField(blank=True, default='', max_length=255)),
                ('label_override', models.CharField(blank=True, default='', max_length=255)),
                ('default_override', models.JSONField(blank=True, default=dict)),
                ('options_override', models.JSONField(blank=True, default=list)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_advanced', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_bindings', to='ai_providers.aimodel')),
                ('canonical_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_bindings', to='ai_providers.canonicalparameter')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('ai_model', 'canonical_parameter'), ('ai_model', 'placeholder')},
            },
        ),
    ]
