# Generated by Django 5.0.7 on 2026-03-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0005_backfill_ai_model_admin_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelparameterbinding',
            name='ui_control_override',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Override control for this model (select, toggle_group, etc). Empty = use canonical default.',
                max_length=100,
            ),
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'ordering': ['provider', 'name'], 'verbose_name': 'AI модель', 'verbose_name_plural': 'AI модели'},
        ),
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['name'], 'verbose_name': 'AI провайдер', 'verbose_name_plural': 'AI провайдеры'},
        ),
    ]
