# Generated by Django 5.0.7 on 2026-03-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0006_add_ui_control_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='response_format',
            field=models.CharField(choices=[('standard', 'Standard (data.state)'), ('veo', 'VEO (data.successFlag)')], default='standard', help_text='Формат ответа при проверке статуса генерации', max_length=20, verbose_name='Формат ответа API'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='status_check_endpoint',
            field=models.CharField(blank=True, default='', help_text='Путь для polling статуса. Пусто = /api/v1/jobs/recordInfo (стандарт Kie.ai). Для VEO: /api/v1/veo/record-info', max_length=255, verbose_name='Эндпоинт проверки статуса'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='image_inputs_schema',
            field=models.JSONField(blank=True, default=list, help_text='Два формата:\n1) Список слотов: [{"key": "input_urls", "label": "...", "min": 0, "max": 4}]\n2) Группы: {"mode": "groups", "no_images_params": {...}, "groups": [{...}]}', verbose_name='Схема входных изображений'),
        ),
    ]
