# Generated by Django 5.0.7 on 2026-03-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0007_add_status_check_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='response_format',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='response_mapping',
            field=models.JSONField(blank=True, default=dict, help_text='Как парсить ответ провайдера. Пусто = стандарт Kie.ai.\nПоля: state_path, success_value, failed_values, result_url_path, error_path.\nПример VEO: {"state_path": "data.successFlag", "success_value": 1, "failed_values": [2, 3], "result_url_path": "data.response.resultUrls.0", "error_path": "data.errorMessage"}', verbose_name='Маппинг ответа API'),
        ),
    ]
