# Generated by Django 5.0.7 on 2026-03-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0008_replace_response_format_with_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='preview_url',
            field=models.CharField(blank=True, help_text='URL или путь к превью-картинке, например: /images/models/veo_3_1_fast.png или https://...', max_length=500, verbose_name='URL превью'),
        ),
    ]
