# Generated by Django 5.0.7 on 2026-04-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_providers', '0009_change_preview_url_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Veo 3.1, Flux 2, Kling', max_length=100, verbose_name='Название семейства')),
                ('model_type', models.CharField(choices=[('IMAGE', 'Изображение'), ('VIDEO', 'Видео')], max_length=10, verbose_name='Тип модели')),
                ('preview_url', models.CharField(blank=True, help_text='Превью-картинка для карточки семейства в пикере', max_length=500, verbose_name='URL превью')),
                ('description', models.TextField(blank=True, help_text='Описание семейства для пикера', verbose_name='Описание')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Бейджи для карточки семейства', verbose_name='Теги')),
                ('variant_ui_control', models.CharField(choices=[('pills', 'Кнопки (pills)'), ('select', 'Выпадающий список (select)')], default='pills', help_text='Как пользователь переключает варианты: кнопки или выпадающий список', max_length=20, verbose_name='Тип переключателя вариантов')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено — все варианты семейства скрыты', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Семейство моделей',
                'verbose_name_plural': 'Семейства моделей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_default_variant',
            field=models.BooleanField(default=False, help_text='Какой вариант выбирается при клике на семейство в пикере', verbose_name='Вариант по умолчанию'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='variant_label',
            field=models.CharField(blank=True, help_text='Короткое название: Fast, Quality, Pro, v2', max_length=100, verbose_name='Название варианта'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='variant_sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок в переключателе вариантов', verbose_name='Порядок варианта'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Принадлежность к семейству. Пусто = standalone модель.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='ai_providers.modelfamily', verbose_name='Семейство'),
        ),
    ]
