# Generated by Django 5.0.7 on 2026-02-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('ACTIVE', 'В работе'), ('PAUSED', 'На паузе'), ('COMPLETED', 'Завершён')], default='ACTIVE', help_text='Статус проекта', max_length=20, verbose_name='Статус')),
                ('aspect_ratio', models.CharField(choices=[('16:9', 'Горизонтальный'), ('9:16', 'Вертикальный')], default='16:9', help_text='Соотношение сторон кадров в проекте', max_length=10, verbose_name='Формат кадра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
