# Generated by Django 5.0.7 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'В работе'), ('PAUSED', 'На паузе'), ('COMPLETED', 'Завершён')], default='ACTIVE', help_text='Статус проекта', max_length=20, verbose_name='Статус'),
        ),
    ]
