# Generated by Django 5.0.7 on 2026-02-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='aspect_ratio',
            field=models.CharField(choices=[('16:9', 'Горизонтальный'), ('9:16', 'Вертикальный')], default='16:9', help_text='Соотношение сторон кадров в проекте', max_length=10, verbose_name='Формат кадра'),
        ),
    ]
