# Generated by Django 5.0.7 on 2026-04-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_new', 'Новый комментарий'), ('reaction_new', 'Новая реакция'), ('generation_completed', 'Генерация завершена'), ('generation_failed', 'Ошибка генерации')], max_length=30),
        ),
    ]
