# Generated by Django 5.0.7 on 2026-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_review_new_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment_new', 'Новый комментарий'), ('reaction_new', 'Новая реакция'), ('review_new', 'Новое решение по ревью'), ('generation_completed', 'Генерация завершена'), ('generation_failed', 'Ошибка генерации'), ('upload_completed', 'Загрузка завершена'), ('feedback_new', 'Новое обращение'), ('feedback_reply', 'Ответ на обращение'), ('feedback_reward', 'Награда за обратную связь')], max_length=30),
        ),
    ]
