# Generated by Django 5.0.7 on 2026-02-10 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_projects', models.IntegerField(default=5, help_text='Максимальное количество проектов пользователя', verbose_name='Максимум проектов')),
                ('max_boxes_per_project', models.IntegerField(default=20, help_text='Максимальное количество боксов в одном проекте', verbose_name='Максимум боксов на проект')),
                ('max_assets_per_box', models.IntegerField(default=10, help_text='Максимальное количество ассетов в одном боксе', verbose_name='Максимум ассетов на бокс')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quota', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Квота пользователя',
                'verbose_name_plural': 'Квоты пользователей',
            },
        ),
    ]
