# Generated by Django 5.0.7 on 2026-03-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_balance_user_pricing_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='storage_limit_bytes',
            field=models.BigIntegerField(default=314572800, help_text='Максимальный объём файлов в S3. По умолчанию 300 МБ.', verbose_name='Лимит хранилища (байт)'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='max_elements_per_scene',
            field=models.IntegerField(default=10, help_text='Максимальное количество элементов в одной группе', verbose_name='Макс. элементов в группе'),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='max_scenes_per_project',
            field=models.IntegerField(default=20, help_text='Максимальное количество групп в одном проекте', verbose_name='Макс. групп в проекте'),
        ),
    ]
