# Generated by Django 5.0.7 on 2026-04-08 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuota',
        ),
    ]
