# Generated by Django 5.0.7 on 2026-02-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_PROGRESS', 'В работе'), ('REVIEW', 'На проверке'), ('APPROVED', 'Утверждён')], default='DRAFT', help_text='Статус сцены', max_length=20, verbose_name='Статус')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('headliner', models.ForeignKey(blank=True, help_text='Главный элемент — обложка сцены на сценарном столе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headliner_for_scene', to='elements.element', verbose_name='Лучший элемент')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
