# Generated by Django 5.0.7 on 2026-03-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='scenes.scene',
                verbose_name='Родительская группа',
            ),
        ),
    ]
