# Generated by Django 5.0.7 on 2026-03-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_project_not_null_scene_nullable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scene',
            options={'ordering': ['order_index', 'created_at'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
