# Generated by Django 5.0.7 on 2026-03-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_scene_cascade_delete'),
        ('scenes', '0003_add_parent_and_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='headliner',
            field=models.ForeignKey(blank=True, help_text='Главный элемент — обложка группы на рабочем столе', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headliner_for_scene', to='elements.element', verbose_name='Лучший элемент'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_PROGRESS', 'В работе'), ('REVIEW', 'На проверке'), ('APPROVED', 'Утверждён')], default='DRAFT', help_text='Статус группы', max_length=20, verbose_name='Статус'),
        ),
    ]
