# Generated by Django 5.0.7 on 2026-02-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Бокс (Шот)',
                'verbose_name_plural': 'Боксы (Шоты)',
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
