# Generated by Django 5.0.7 on 2026-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_box_headliner'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('IN_PROGRESS', 'В работе'), ('REVIEW', 'На проверке'), ('APPROVED', 'Утверждён')], default='DRAFT', help_text='Статус бокса', max_length=20, verbose_name='Статус'),
        ),
    ]
