# Generated by Django 5.0.7 on 2026-04-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_migrate_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_elements_per_scene',
        ),
    ]
