# Generated by Django 5.0.7 on 2026-04-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_max_elements_per_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='trial_bonus_credits',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Бонусные кадры при регистрации (0 = не начислять)', max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_duration_days',
            field=models.PositiveIntegerField(default=7, help_text='Длительность пробного периода в днях (используется только для плана с is_trial_reference)'),
        ),
    ]
