# Generated by Django 5.0.7 on 2026-02-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(choices=[('IMAGE', 'Изображение'), ('VIDEO', 'Видео')], max_length=10, verbose_name='Тип элемента')),
                ('order_index', models.IntegerField(default=0, help_text='Порядок отображения элемента внутри сцены', verbose_name='Порядковый номер')),
                ('file_url', models.URLField(blank=True, max_length=500, verbose_name='URL файла')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, verbose_name='URL превью')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('prompt_text', models.TextField(blank=True, verbose_name='Текст промпта')),
                ('generation_config', models.JSONField(blank=True, default=dict, help_text='Выбранные параметры генерации (width, height, steps, и т.д.)', verbose_name='Конфигурация генерации')),
                ('seed', models.IntegerField(blank=True, help_text='Seed для воспроизводимости генерации', null=True, verbose_name='Seed')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидание'), ('PROCESSING', 'Обработка'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка')], default='PENDING', help_text='Статус генерации элемента', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, help_text='Детали ошибки при генерации', verbose_name='Сообщение об ошибке')),
                ('source_type', models.CharField(choices=[('GENERATED', 'Сгенерировано AI'), ('UPLOADED', 'Загружено пользователем'), ('IMG2VID', 'Img2Vid преобразование')], default='GENERATED', help_text='Способ создания элемента', max_length=20, verbose_name='Тип источника')),
                ('external_task_id', models.CharField(blank=True, db_index=True, help_text='Task ID от Kie.ai или другого провайдера', max_length=255, verbose_name='ID задачи у провайдера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ai_model', models.ForeignKey(blank=True, help_text='Модель, которая сгенерировала этот элемент', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_elements', to='ai_providers.aimodel', verbose_name='AI Модель')),
                ('parent_element', models.ForeignKey(blank=True, help_text='Исходный элемент для img2vid или вариаций', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_elements', to='elements.element', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
