# Generated by Django 5.0.7 on 2026-02-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='scenes.scene', verbose_name='Сцена'),
        ),
    ]
