# Generated by Django 5.0.7 on 2026-03-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='parent_element',
        ),
    ]
