# Generated by Django 5.0.7 on 2026-03-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_remove_parent_element'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projects.project', verbose_name='Проект'),
        ),
    ]
