# Generated by Django 5.0.7 on 2026-03-21 07:24

from django.db import migrations


def backfill_project(apps, schema_editor):
    schema_editor.execute(
        "UPDATE elements_element "
        "SET project_id = ("
        "  SELECT project_id FROM scenes_scene "
        "  WHERE scenes_scene.id = elements_element.scene_id"
        ")"
    )


def reverse(apps, schema_editor):
    pass  # project field will be removed on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_add_project_fk'),
    ]

    operations = [
        migrations.RunPython(backfill_project, reverse),
    ]
