# Generated by Django 5.0.7 on 2026-03-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_backfill_project'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='element',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='scenes.scene', verbose_name='Группа'),
        ),
    ]
