# Generated by Django 5.0.7 on 2026-03-21 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0006_project_not_null_scene_nullable'),
        ('scenes', '0003_add_parent_and_verbose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='order_index',
            field=models.IntegerField(default=0, help_text='Порядок отображения элемента внутри группы', verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='element',
            name='scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='scenes.scene', verbose_name='Группа'),
        ),
    ]
