# Generated by Django 5.0.7 on 2026-03-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_fix_scene_cascade_db_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Размер файла (байт)'),
        ),
    ]
