# Generated by Django 5.0.7 on 2026-03-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_add_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='preview_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='element',
            name='upload_keys',
            field=models.JSONField(blank=True, help_text='S3 keys for presigned upload: {original, small, medium}', null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('PROCESSING', 'Обработка'), ('COMPLETED', 'Завершено'), ('FAILED', 'Ошибка'), ('UPLOADING', 'Загрузка')], default='PENDING', help_text='Статус генерации элемента', max_length=20, verbose_name='Статус'),
        ),
    ]
