# Generated by Django 5.0.7 on 2026-04-05 05:36

from django.db import migrations, models


def convert_img2vid(apps, schema_editor):
    Element = apps.get_model('elements', 'Element')
    Element.objects.filter(source_type='IMG2VID').update(source_type='GENERATED')


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_add_preview_url_upload_keys_uploading_status'),
    ]

    operations = [
        migrations.RunPython(convert_img2vid, migrations.RunPython.noop),
        migrations.AddField(
            model_name='element',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'В работе'), ('NEEDS_REVIEW', 'На согласовании'), ('APPROVED', 'Одобрено'), ('CHANGES_REQUESTED', 'На доработку'), ('REJECTED', 'Отклонено')], default=None, max_length=20, null=True, verbose_name='Статус согласования'),
        ),
        migrations.AddField(
            model_name='element',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Оригинальное имя файла'),
        ),
        migrations.AlterField(
            model_name='element',
            name='source_type',
            field=models.CharField(choices=[('GENERATED', 'Сгенерировано AI'), ('UPLOADED', 'Загружено пользователем')], default='GENERATED', help_text='Способ создания элемента', max_length=20, verbose_name='Тип источника'),
        ),
    ]
