# Generated by Django 5.0.7 on 2026-04-05 09:05

from django.db import migrations, models


def convert_old_statuses(apps, schema_editor):
    Element = apps.get_model('elements', 'Element')
    Element.objects.filter(
        approval_status__in=['NEEDS_REVIEW', 'CHANGES_REQUESTED']
    ).update(approval_status='IN_PROGRESS')
    Element.objects.filter(approval_status='REJECTED').update(approval_status=None)


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0011_remove_img2vid_add_approval_status'),
    ]

    operations = [
        migrations.RunPython(convert_old_statuses, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='element',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('IN_PROGRESS', 'В работе'), ('APPROVED', 'Согласовано')], default=None, max_length=20, null=True, verbose_name='Статус согласования'),
        ),
    ]
