# Generated by Django 5.0.7 on 2026-04-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('openai_compatible', 'OpenAI-compatible'), ('anthropic', 'Anthropic')], max_length=20)),
                ('api_base_url', models.URLField()),
                ('api_key', models.CharField(help_text='API-ключ. Префикс ENV: читает из переменной окружения.', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM-провайдер',
                'verbose_name_plural': 'LLM-провайдеры',
            },
        ),
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('PROMPT_ENHANCE', 'Улучшение промпта'), ('SMART_EDIT', 'Умное редактирование')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('system_prompt', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('cost_per_call', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='ai_services.llmprovider')),
            ],
            options={
                'verbose_name': 'AI-сервис',
                'verbose_name_plural': 'AI-сервисы',
            },
        ),
        migrations.AddConstraint(
            model_name='aiservice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('service_type',), name='unique_active_service_per_type'),
        ),
    ]
