# Generated by Django 5.0.7 on 2026-04-09 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('icon', models.CharField(default='circle-dot', max_length=50, verbose_name='Иконка (Lucide)')),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Награда (кадров)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('category', models.CharField(choices=[('onboarding', 'Первые шаги'), ('feature', 'Возможности'), ('milestone', 'Достижения')], default='onboarding', max_length=20)),
                ('trigger_type', models.CharField(choices=[('backend_signal', 'Авто (бэкенд)'), ('frontend_action', 'По действию (фронт)')], default='backend_signal', max_length=20)),
                ('trigger_event', models.CharField(blank=True, default='', max_length=100)),
                ('empty_state_title', models.CharField(blank=True, default='', max_length=120, verbose_name='Заголовок пустого экрана')),
                ('empty_state_desc', models.CharField(blank=True, default='', max_length=200, verbose_name='Описание пустого экрана')),
                ('empty_state_cta', models.CharField(blank=True, default='', max_length=60, verbose_name='Кнопка пустого экрана')),
                ('empty_state_page', models.CharField(blank=True, default='', max_length=20, verbose_name='Страница')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_seen', models.BooleanField(default=False)),
                ('backfill_done', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Состояние онбординга',
                'verbose_name_plural': 'Состояния онбординга',
            },
        ),
        migrations.CreateModel(
            name='UserTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('reward_paid', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='onboarding.onboardingtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Выполнение задания',
                'verbose_name_plural': 'Выполнения заданий',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
