# Generated by Django 5.0.7 on 2026-04-08 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_creditstransaction_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstransaction',
            name='reason',
            field=models.CharField(choices=[('admin_topup', 'Пополнение администратором'), ('admin_adjustment', 'Корректировка администратором'), ('generation_debit', 'Списание за генерацию'), ('generation_refund', 'Возврат за генерацию'), ('refund_provider_error', 'Возврат: ошибка провайдера'), ('refund_pricing_failure', 'Возврат: ошибка ценообразования'), ('payment_topup', 'Пополнение (онлайн-оплата)')], max_length=64, verbose_name='Причина'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yookassa_payment_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID платежа ЮKassa')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('payment_method_type', models.CharField(choices=[('sbp', 'СБП'), ('bank_card', 'Банковская карта'), ('sberbank', 'SberPay')], max_length=32, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('waiting_for_capture', 'Ожидание подтверждения'), ('succeeded', 'Успешно'), ('canceled', 'Отменено'), ('expired', 'Истекло')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('credits_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='credits.creditstransaction', verbose_name='Транзакция кредитов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yookassa_payment_id', models.CharField(db_index=True, max_length=64, verbose_name='ID платежа ЮKassa')),
                ('event_type', models.CharField(max_length=64, verbose_name='Тип события')),
                ('raw_body', models.JSONField(verbose_name='Сырые данные')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('processing_result', models.CharField(choices=[('ok', 'Обработано'), ('error', 'Ошибка'), ('duplicate', 'Дубликат'), ('ip_rejected', 'IP отклонён')], max_length=20, verbose_name='Результат обработки')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('processing_time_ms', models.PositiveIntegerField(null=True, verbose_name='Время обработки (мс)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='credits.payment', verbose_name='Платёж')),
            ],
            options={
                'verbose_name': 'Лог webhook',
                'verbose_name_plural': 'Логи webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='credits_pay_user_id_486880_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='credits_pay_status_d74cb6_idx'),
        ),
    ]
