# Generated by Django 5.0.7 on 2026-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_creditstransaction_reason_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstransaction',
            name='reason',
            field=models.CharField(choices=[('admin_topup', 'Пополнение администратором'), ('admin_adjustment', 'Корректировка администратором'), ('generation_debit', 'Списание за генерацию'), ('generation_refund', 'Возврат за генерацию'), ('refund_provider_error', 'Возврат: ошибка провайдера'), ('refund_pricing_failure', 'Возврат: ошибка ценообразования'), ('payment_topup', 'Пополнение (онлайн-оплата)'), ('trial_bonus', 'Бонус за триал')], max_length=64, verbose_name='Причина'),
        ),
    ]
