# Generated by Django 5.0.7 on 2026-04-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_add_trial_bonus_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='is_trusted_ip',
            field=models.BooleanField(default=False, verbose_name='Доверенный IP'),
        ),
        migrations.AlterField(
            model_name='paymentwebhooklog',
            name='processing_result',
            field=models.CharField(blank=True, choices=[('ok', 'Обработано'), ('error', 'Ошибка'), ('duplicate', 'Дубликат'), ('ip_rejected', 'IP отклонён')], default='', max_length=32, verbose_name='Результат обработки'),
        ),
    ]
