# Generated by Django 5.0.7 on 2026-04-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_add_webhook_is_trusted_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditstransaction',
            name='reason',
            field=models.CharField(choices=[('admin_topup', 'Пополнение администратором'), ('admin_adjustment', 'Корректировка администратором'), ('generation_debit', 'Списание за генерацию'), ('generation_refund', 'Возврат за генерацию'), ('refund_provider_error', 'Возврат: ошибка провайдера'), ('refund_pricing_failure', 'Возврат: ошибка ценообразования'), ('payment_topup', 'Пополнение (онлайн-оплата)'), ('trial_bonus', 'Бонус за триал'), ('feedback_reward', 'Награда за обратную связь'), ('prompt_enhancement', 'Усиление промпта')], max_length=64, verbose_name='Причина'),
        ),
    ]
